name: Build Platform Image

on:
  workflow_call:
    inputs:
      mvnd_version:
        required: true
        type: string
      tag_version:
        required: true
        type: string
      jdk_type:
        required: true
        type: string
        description: 'JDK type (e.g., temurin-8-jdk-jammy, temurin-17-jdk-jammy)'
      base_image:
        required: true
        type: string
        description: 'Base Docker image (e.g., eclipse-temurin:8-jdk-jammy)'
      platforms:
        required: true
        type: string
        description: 'Comma-separated list of platforms (e.g., linux/amd64,darwin/amd64,darwin/arm64)'
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare Build Args 
        id: build_args
        run: |
          MVND_VERSION="${{ inputs.mvnd_version }}"
          TAG_VERSION="${{ inputs.tag_version }}"
          
          echo "Building for JDK: ${{ inputs.jdk_type }}"
          echo "Base image: ${{ inputs.base_image }}"
          echo "Platforms: ${{ inputs.platforms }}"
          echo "Tag version: $TAG_VERSION"
          
          # Generate URLs for each platform (mvnd doesn't support linux/arm64)
          LINUX_AMD64_URL="https://github.com/apache/maven-mvnd/releases/download/$MVND_VERSION/maven-mvnd-$MVND_VERSION-linux-amd64.zip"
          DARWIN_AMD64_URL="https://github.com/apache/maven-mvnd/releases/download/$MVND_VERSION/maven-mvnd-$MVND_VERSION-darwin-amd64.zip"
          DARWIN_ARM64_URL="https://github.com/apache/maven-mvnd/releases/download/$MVND_VERSION/maven-mvnd-$MVND_VERSION-darwin-aarch64.zip"
          
          echo "linux_amd64_url=$LINUX_AMD64_URL" >> $GITHUB_OUTPUT
          echo "darwin_amd64_url=$DARWIN_AMD64_URL" >> $GITHUB_OUTPUT
          echo "darwin_arm64_url=$DARWIN_ARM64_URL" >> $GITHUB_OUTPUT
          
          echo "Generated URLs:"
          echo "Linux AMD64: $LINUX_AMD64_URL"
          echo "Darwin AMD64: $DARWIN_AMD64_URL"
          echo "Darwin ARM64: $DARWIN_ARM64_URL"

      - name: Validate URLs
        run: |
          echo "Testing URL accessibility..."
          
          LINUX_AMD64_URL="${{ steps.build_args.outputs.linux_amd64_url }}"
          DARWIN_AMD64_URL="${{ steps.build_args.outputs.darwin_amd64_url }}"
          DARWIN_ARM64_URL="${{ steps.build_args.outputs.darwin_arm64_url }}"
          
          if curl -f -I "$LINUX_AMD64_URL" > /dev/null 2>&1; then
            echo "✅ Linux AMD64 URL is accessible"
          else
            echo "❌ Linux AMD64 URL is not accessible"
            echo "Trying to get more info..."
            curl -v "$LINUX_AMD64_URL" 2>&1 | head -20
          fi
          
          if curl -f -I "$DARWIN_AMD64_URL" > /dev/null 2>&1; then
            echo "✅ Darwin AMD64 URL is accessible"
          else
            echo "❌ Darwin AMD64 URL is not accessible"
            echo "Trying to get more info..."
            curl -v "$DARWIN_AMD64_URL" 2>&1 | head -20
          fi
          
          if curl -f -I "$DARWIN_ARM64_URL" > /dev/null 2>&1; then
            echo "✅ Darwin ARM64 URL is accessible"
          else
            echo "❌ Darwin ARM64 URL is not accessible"
            echo "Trying to get more info..."
            curl -v "$DARWIN_ARM64_URL" 2>&1 | head -20
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ inputs.platforms }}
          push: true
          tags: power4j/mvnd:${{ inputs.tag_version }}-${{ inputs.jdk_type }}
          build-args: |
            MVND_URL_LINUX_AMD64=${{ steps.build_args.outputs.linux_amd64_url }}
            MVND_URL_DARWIN_AMD64=${{ steps.build_args.outputs.darwin_amd64_url }}
            MVND_URL_DARWIN_ARM64=${{ steps.build_args.outputs.darwin_arm64_url }}
            BASE_IMAGE=${{ inputs.base_image }} 