name: CI Build

on:
  push:
    branches: [ main, develop, master, dev ]
  pull_request:
    branches: [ main, develop, master, dev ]
  workflow_dispatch:
    inputs:
      mvnd_version:
        description: 'mvnd version to use (see releases: https://github.com/apache/maven-mvnd/releases)'
        required: false
        default: '1.0.2'
        type: string
      tag_version:
        description: 'Image version prefix for testing'
        required: false
        default: 'dev'
        type: string

jobs:
  test-temurin-8:
    uses: ./.github/workflows/docker-build.yml
    with:
      mvnd_version: ${{ github.event.inputs.mvnd_version || '1.0.2' }}
      tag_version: ${{ github.event.inputs.tag_version || 'dev' }}
      jdk_type: temurin-8-jdk-jammy
      base_image: eclipse-temurin:8-jdk-jammy
      platforms: linux/amd64
      push_image: false

  test-temurin-17:
    uses: ./.github/workflows/docker-build.yml
    with:
      mvnd_version: ${{ github.event.inputs.mvnd_version || '1.0.2' }}
      tag_version: ${{ github.event.inputs.tag_version || 'dev' }}
      jdk_type: temurin-17-jdk-jammy
      base_image: eclipse-temurin:17-jdk-jammy
      platforms: linux/amd64
      push_image: false

  test-temurin-22:
    uses: ./.github/workflows/docker-build.yml
    with:
      mvnd_version: ${{ github.event.inputs.mvnd_version || '1.0.2' }}
      tag_version: ${{ github.event.inputs.tag_version || 'dev' }}
      jdk_type: temurin-22-jdk-jammy
      base_image: eclipse-temurin:22-jdk-jammy
      platforms: linux/amd64
      push_image: false

