name: Platform Build

on:
  workflow_dispatch:
    inputs:
      mvnd_version:
        description: 'mvnd version to use (see releases: https://github.com/apache/maven-mvnd/releases)'
        required: true
        default: '1.0.2'
      tag-version:
        description: 'Image version prefix,use mvnd_version if empty'
        required: false
        default: ''
      all_jdk:
        description: 'build all'
        required: false
        type: boolean
        default: false
      temurin-8-jdk-jammy:
        description: 'use clipse-temurin:8-jdk-jammy'
        required: false
        type: boolean
        default: false
      temurin-17-jdk-jammy:
        description: 'use clipse-temurin:17-jdk-jammy'
        required: false
        type: boolean
        default: false

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: |
          echo "mvnd_version: ${{ github.event.inputs.mvnd_version }}"
          echo "tag-version: ${{ github.event.inputs.tag-version }}"
          echo "all_jdk: ${{ github.event.inputs.all_jdk }}"
          echo "temurin-8-jdk-jammy: ${{ github.event.inputs.temurin-8-jdk-jammy }}"
          echo "temurin-17-jdk-jammy: ${{ github.event.inputs.temurin-17-jdk-jammy }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Prepare Build Args 
        id: build_args
        run: |
          MVND_VERSION="${{ github.event.inputs.mvnd_version }}"
          TAG_VERSION="${{ github.event.inputs.tag-version }}"
          
          # Use tag-version if provided, otherwise use mvnd_version
          if [ -z "$TAG_VERSION" ]; then
            TAG_VERSION="$MVND_VERSION"
          fi
          
          echo "tag_version=$TAG_VERSION" >> $GITHUB_OUTPUT
          echo "Using tag version: $TAG_VERSION"
          
          # Generate URLs for each platform
          LINUX_AMD64_URL="https://github.com/apache/maven-mvnd/releases/download/$MVND_VERSION/maven-mvnd-$MVND_VERSION-linux-amd64.zip"
          LINUX_ARM64_URL="https://github.com/apache/maven-mvnd/releases/download/$MVND_VERSION/maven-mvnd-$MVND_VERSION-linux-arm64.zip"
          
          echo "linux_amd64_url=$LINUX_AMD64_URL" >> $GITHUB_OUTPUT
          echo "linux_arm64_url=$LINUX_ARM64_URL" >> $GITHUB_OUTPUT
          
          echo "Generated URLs:"
          echo "Linux AMD64: $LINUX_AMD64_URL"
          echo "Linux ARM64: $LINUX_ARM64_URL"

      - name: Build(temurin-8-jdk-jammy)
        if: inputs.all_jdk || inputs.temurin-8-jdk-jammy
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: power4j/mvnd:${{ steps.build_args.outputs.tag_version }}-temurin-8-jdk-jammy
          build-args: |
            MVND_URL_LINUX_AMD64=${{ steps.build_args.outputs.linux_amd64_url }}
            MVND_URL_LINUX_ARM64=${{ steps.build_args.outputs.linux_arm64_url }}
            BASE_IMAGE="eclipse-temurin:8-jdk-jammy"

      - name: Build(temurin-17-jdk-jammy)
        if: inputs.all_jdk || inputs.temurin-17-jdk-jammy
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: power4j/mvnd:${{ steps.build_args.outputs.tag_version }}-temurin-17-jdk-jammy
          build-args: |
            MVND_URL_LINUX_AMD64=${{ steps.build_args.outputs.linux_amd64_url }}
            MVND_URL_LINUX_ARM64=${{ steps.build_args.outputs.linux_arm64_url }}
            BASE_IMAGE="eclipse-temurin:17-jdk-jammy"