name: Build and Push to Docker Hub

on:
  workflow_dispatch:
    inputs:
      mvnd_version:
        description: 'version to build (see releases: https://github.com/apache/maven-mvnd/releases)'
        required: true
        default: 'latest'
      all_platforms:
        description: 'Select all supported platforms and JDK versions'
        required: false
        type: boolean
        default: false
      linux_amd64_jdk8:
        description: 'Build for linux/amd64 with JDK8'
        required: false
        type: boolean
        default: false
      linux_amd64_jdk17:
        description: 'Build for linux/amd64 with JDK17'
        required: false
        type: boolean
        default: false
      windows_amd64_jdk8:
        description: 'Build for windows/amd64 with JDK8'
        required: false
        type: boolean
        default: false
      windows_amd64_jdk17:
        description: 'Build for windows/amd64 with JDK17'
        required: false
        type: boolean
        default: false
      darwin_amd64_jdk8:
        description: 'Build for darwin/amd64 with JDK8'
        required: false
        type: boolean
        default: false
      darwin_amd64_jdk17:
        description: 'Build for darwin/amd64 with JDK17'
        required: false
        type: boolean
        default: false
      darwin_aarch64_jdk8:
        description: 'Build for darwin/aarch64 with JDK8'
        required: false
        type: boolean
        default: false
      darwin_aarch64_jdk17:
        description: 'Build for darwin/aarch64 with JDK17'
        required: false
        type: boolean
        default: false

jobs:
  build-linux-amd64-jdk8:
    if: inputs.all_platforms || inputs.linux_amd64_jdk8
    uses: ./.github/workflows/build-platform.yml
    with:
      platform: linux/amd64
      jdk: jdk8
      mvnd_version: ${{ inputs.mvnd_version }}
      base_image: eclipse-temurin:8-jdk-jammy
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-linux-amd64-jdk17:
    if: inputs.all_platforms || inputs.linux_amd64_jdk17
    uses: ./.github/workflows/build-platform.yml
    with:
      platform: linux/amd64
      jdk: jdk17
      mvnd_version: ${{ inputs.mvnd_version }}
      base_image: eclipse-temurin:17-jdk-jammy
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-windows-amd64-jdk8:
    if: inputs.all_platforms || inputs.windows_amd64_jdk8
    uses: ./.github/workflows/build-platform.yml
    with:
      platform: windows/amd64
      jdk: jdk8
      mvnd_version: ${{ inputs.mvnd_version }}
      base_image: eclipse-temurin:8-jdk-windowsservercore-ltsc2022
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-windows-amd64-jdk17:
    if: inputs.all_platforms || inputs.windows_amd64_jdk17
    uses: ./.github/workflows/build-platform.yml
    with:
      platform: windows/amd64
      jdk: jdk17
      mvnd_version: ${{ inputs.mvnd_version }}
      base_image: eclipse-temurin:17-jdk-windowsservercore-ltsc2022
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-darwin-amd64-jdk8:
    if: inputs.all_platforms || inputs.darwin_amd64_jdk8
    uses: ./.github/workflows/build-platform.yml
    with:
      platform: darwin/amd64
      jdk: jdk8
      mvnd_version: ${{ inputs.mvnd_version }}
      base_image: eclipse-temurin:8-jdk-jammy
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-darwin-amd64-jdk17:
    if: inputs.all_platforms || inputs.darwin_amd64_jdk17
    uses: ./.github/workflows/build-platform.yml
    with:
      platform: darwin/amd64
      jdk: jdk17
      mvnd_version: ${{ inputs.mvnd_version }}
      base_image: eclipse-temurin:17-jdk-jammy
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-darwin-aarch64-jdk8:
    if: inputs.all_platforms || inputs.darwin_aarch64_jdk8
    uses: ./.github/workflows/build-platform.yml
    with:
      platform: darwin/aarch64
      jdk: jdk8
      mvnd_version: ${{ inputs.mvnd_version }}
      base_image: eclipse-temurin:8-jdk-jammy
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-darwin-aarch64-jdk17:
    if: inputs.all_platforms || inputs.darwin_aarch64_jdk17
    uses: ./.github/workflows/build-platform.yml
    with:
      platform: darwin/aarch64
      jdk: jdk17
      mvnd_version: ${{ inputs.mvnd_version }}
      base_image: eclipse-temurin:17-jdk-jammy
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}